#!/usr/bin/env bash
# nx-android-streamer — starter script
# Brings up a headless Waydroid session at phone geometry, ready for a streamer.
# Subcommands: setup | arm | up | down | status | ref
set -euo pipefail

W=${NXAS_WIDTH:-1080}
H=${NXAS_HEIGHT:-2400}
HZ=${NXAS_HZ:-90}

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUN="$ROOT/.run"
mkdir -p "$RUN"

PROP=/var/lib/waydroid/waydroid_base.prop

log() { printf '\033[38;2;119;0;255m[nxas]\033[0m %s\n' "$*"; }
die() { printf '\033[31m[nxas]\033[0m %s\n' "$*" >&2; exit 1; }

need() { command -v "$1" >/dev/null 2>&1; }

# ---------------------------------------------------------------- setup ----
cmd_setup() {
    log "checking kernel binder support..."
    if zgrep -q 'CONFIG_ANDROID_BINDER_IPC=y' /proc/config.gz 2>/dev/null; then
        log "  binder: built-in ✓"
    else
        die "kernel lacks CONFIG_ANDROID_BINDER_IPC — install a binder-enabled kernel (cachyos/zen) first"
    fi

    local pkgs=()
    need waydroid    || pkgs+=(waydroid)
    need sway        || pkgs+=(sway)
    need wf-recorder || pkgs+=(wf-recorder)
    need grim        || pkgs+=(grim)
    need vainfo      || pkgs+=(libva-utils)
    need gst-launch-1.0 || pkgs+=(gstreamer gst-plugins-good gst-plugins-bad gst-plugin-va gst-plugin-pipewire)
    pacman -Q gst-plugins-ugly &>/dev/null || pkgs+=(gst-plugins-ugly)   # x264enc software fallback
    python -c 'import aiohttp' 2>/dev/null || pkgs+=(python-aiohttp)
    python -c 'import evdev'   2>/dev/null || pkgs+=(python-evdev)
    if ((${#pkgs[@]})); then
        log "installing: ${pkgs[*]}"
        sudo pacman -S --needed "${pkgs[@]}" || die "pacman failed — AUR-only package? try paru -S ${pkgs[*]}"
    else
        log "  packages: all present ✓"
    fi

    if [[ ! -f /var/lib/waydroid/waydroid.cfg ]]; then
        log "initializing waydroid with GAPPS image (downloads ~1 GB)..."
        sudo waydroid init -s GAPPS
    else
        log "  waydroid: already initialized ✓"
    fi

    log "pinning phone geometry ${W}x${H} in waydroid_base.prop..."
    for kv in "persist.waydroid.width=$W" \
              "persist.waydroid.height=$H" \
              "persist.waydroid.multi_windows=false"; do
        key=${kv%%=*}
        if sudo grep -q "^${key}=" "$PROP" 2>/dev/null; then
            sudo sed -i "s|^${key}=.*|${kv}|" "$PROP"
        else
            echo "$kv" | sudo tee -a "$PROP" >/dev/null
        fi
    done

    sudo systemctl enable --now waydroid-container.service
    log "setup done. next: ./start.sh arm   (ARM app translation), then ./start.sh up"
}

# ------------------------------------------------------------------ arm ----
cmd_arm() {
    # ARM translation + Widevine via casualsnek/waydroid_script (GPL-3.0).
    # Used as a tool, not vendored — see BORROWED.md.
    local ws="$RUN/waydroid_script"
    if [[ ! -d $ws ]]; then
        log "cloning casualsnek/waydroid_script..."
        git clone --depth 1 https://github.com/casualsnek/waydroid_script "$ws"
    fi
    cd "$ws"
    python -m venv venv 2>/dev/null || true
    ./venv/bin/pip install -q -r requirements.txt
    log "installing libndk (ARM translation for AMD) + widevine..."
    sudo ./venv/bin/python main.py install libndk widevine
    log "done. For Play Store login, also run:"
    log "  sudo $ws/venv/bin/python main.py certified"
    log "and register the printed android_id at https://www.google.com/android/uncertified"
}

# ------------------------------------------------------------------- up ----
cmd_up() {
    systemctl is-active -q waydroid-container.service \
        || sudo systemctl start waydroid-container.service

    if [[ -f $RUN/sway.pid ]] && kill -0 "$(cat "$RUN/sway.pid")" 2>/dev/null; then
        log "already up (sway pid $(cat "$RUN/sway.pid"), display $(cat "$RUN/wayland-display" 2>/dev/null || echo '?'))"
        return
    fi

    cat > "$RUN/sway.conf" <<EOF
# generated by start.sh — headless phone-geometry session for waydroid
output HEADLESS-1 mode --custom ${W}x${H}@${HZ}Hz
output HEADLESS-1 bg #0a0a12 solid_color
default_border none
xwayland disable
exec waydroid show-full-ui
EOF

    log "starting headless sway (${W}x${H}@${HZ})..."
    # NOTE: 'headless,libinput' is load-bearing. Plain 'headless' has no input
    # backend, so injected uinput touch devices would go nowhere.
    WLR_BACKENDS=headless,libinput WLR_LIBINPUT_NO_DEVICES=1 \
        sway -c "$RUN/sway.conf" >"$RUN/sway.log" 2>&1 &
    echo $! > "$RUN/sway.pid"

    local disp=""
    for _ in $(seq 1 50); do
        disp=$(sed -n "s/.*Running compositor on wayland display '\(.*\)'.*/\1/p" "$RUN/sway.log" | head -1)
        [[ -n $disp ]] && break
        kill -0 "$(cat "$RUN/sway.pid")" 2>/dev/null || { tail -5 "$RUN/sway.log" >&2; die "sway died on startup (see .run/sway.log)"; }
        sleep 0.2
    done
    [[ -n $disp ]] || die "couldn't detect sway's wayland display (see .run/sway.log)"
    echo "$disp" > "$RUN/wayland-display"

    log "up ✓  wayland display: $disp — android is booting inside it"
    log "streamer hookup: WAYLAND_DISPLAY=$disp (nx-streamerd / './start.sh ref' for sunshine baseline)"
}

# ----------------------------------------------------------------- down ----
cmd_down() {
    waydroid session stop 2>/dev/null || true
    if [[ -f $RUN/sway.pid ]]; then
        kill "$(cat "$RUN/sway.pid")" 2>/dev/null || true
        rm -f "$RUN/sway.pid" "$RUN/wayland-display"
    fi
    log "down."
}

# --------------------------------------------------------------- status ----
cmd_status() {
    printf 'container : %s\n' "$(systemctl is-active waydroid-container.service 2>/dev/null || echo inactive)"
    if [[ -f $RUN/sway.pid ]] && kill -0 "$(cat "$RUN/sway.pid")" 2>/dev/null; then
        printf 'sway      : running (pid %s, display %s, %sx%s@%s)\n' \
            "$(cat "$RUN/sway.pid")" "$(cat "$RUN/wayland-display" 2>/dev/null || echo '?')" "$W" "$H" "$HZ"
    else
        printf 'sway      : not running\n'
    fi
    printf 'session   : %s\n' "$(waydroid status 2>/dev/null | sed -n 's/^Session:[[:space:]]*//p' || echo unknown)"
}

# ------------------------------------------------------------------ ref ----
cmd_ref() {
    # Reference rig: Sunshine capturing our headless session, for latency
    # baselines to beat. Pair from the phone with Moonlight, custom res WxH.
    need sunshine || die "sunshine not installed (pacman -S sunshine) — optional, only for baselines"
    [[ -f $RUN/wayland-display ]] || die "session not up — run ./start.sh up first"
    log "starting sunshine against $(cat "$RUN/wayland-display") — Ctrl-C to stop"
    WAYLAND_DISPLAY=$(cat "$RUN/wayland-display") sunshine
}

# ----------------------------------------------------------------- main ----
case "${1:-help}" in
    setup)  cmd_setup ;;
    arm)    cmd_arm ;;
    up)     cmd_up ;;
    down)   cmd_down ;;
    status) cmd_status ;;
    ref)    cmd_ref ;;
    *)      sed -n '2,4p' "$0" | sed 's/^# //'; exit 1 ;;
esac
