#!/usr/bin/env bash
# nx-android-streamer — starter script
# Brings up a headless Waydroid session at phone geometry, ready for a streamer.
# Subcommands: setup | arm | up | stream | doctor | down | status | ref
set -euo pipefail

W=${NXAS_WIDTH:-1080}
H=${NXAS_HEIGHT:-2400}
HZ=${NXAS_HZ:-90}

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUN="$ROOT/.run"
mkdir -p "$RUN"

PROP=/var/lib/waydroid/waydroid_base.prop

log() { printf '\033[38;2;119;0;255m[nxas]\033[0m %s\n' "$*"; }
die() { printf '\033[31m[nxas]\033[0m %s\n' "$*" >&2; exit 1; }

need() { command -v "$1" >/dev/null 2>&1; }

# ---------------------------------------------------------------- setup ----
cmd_setup() {
    log "checking kernel binder support..."
    if zgrep -q 'CONFIG_ANDROID_BINDER_IPC=y' /proc/config.gz 2>/dev/null; then
        log "  binder: built-in ✓"
    else
        die "kernel lacks CONFIG_ANDROID_BINDER_IPC — install a binder-enabled kernel (cachyos/zen) first"
    fi

    local pkgs=()
    need waydroid    || pkgs+=(waydroid)
    need sway        || pkgs+=(sway)
    need wf-recorder || pkgs+=(wf-recorder)
    need grim        || pkgs+=(grim)
    need vainfo      || pkgs+=(libva-utils)
    need adb         || pkgs+=(android-tools)      # touch injection reaches android over adb
    [[ -f /usr/share/scrcpy/scrcpy-server ]] || pkgs+=(scrcpy)  # its server jar, control-only
    # probe actual elements, not gst-launch — the core can be present while
    # the plugin packages that matter (rtph264pay, vah264enc) are not
    gst-inspect-1.0 rtph264pay &>/dev/null || pkgs+=(gst-plugins-good)
    gst-inspect-1.0 webrtcbin  &>/dev/null || pkgs+=(gst-plugins-bad)
    gst-inspect-1.0 vah264enc  &>/dev/null || pkgs+=(gst-plugin-va)
    gst-inspect-1.0 pipewiresrc &>/dev/null || pkgs+=(gst-plugin-pipewire)
    pacman -Q gst-plugins-ugly &>/dev/null || pkgs+=(gst-plugins-ugly)   # x264enc software fallback
    python -c 'import aiohttp' 2>/dev/null || pkgs+=(python-aiohttp)
    python -c 'import evdev'   2>/dev/null || pkgs+=(python-evdev)
    if ((${#pkgs[@]})); then
        log "installing: ${pkgs[*]}"
        sudo pacman -S --needed "${pkgs[@]}" || die "pacman failed — AUR-only package? try paru -S ${pkgs[*]}"
    else
        log "  packages: all present ✓"
    fi

    if [[ ! -f /var/lib/waydroid/waydroid.cfg ]]; then
        log "initializing waydroid with GAPPS image (downloads ~1 GB)..."
        sudo waydroid init -s GAPPS
    else
        log "  waydroid: already initialized ✓"
    fi
    # waydroid init has been observed to exit 0 with the vendor image missing —
    # verify the download actually completed before letting setup "succeed".
    [[ -f /var/lib/waydroid/images/system.img && -f /var/lib/waydroid/images/vendor.img ]] \
        || die "waydroid images incomplete — re-run: sudo waydroid init -s GAPPS"

    log "pinning phone geometry ${W}x${H} in waydroid_base.prop..."
    for kv in "persist.waydroid.width=$W" \
              "persist.waydroid.height=$H" \
              "persist.waydroid.multi_windows=false"; do
        key=${kv%%=*}
        if sudo grep -q "^${key}=" "$PROP" 2>/dev/null; then
            sudo sed -i "s|^${key}=.*|${kv}|" "$PROP"
        else
            echo "$kv" | sudo tee -a "$PROP" >/dev/null
        fi
    done

    sudo systemctl enable --now waydroid-container.service
    log "setup done. next: ./start.sh arm   (ARM app translation), then ./start.sh up"
}

# ------------------------------------------------------------------ arm ----
cmd_arm() {
    # ARM translation + Widevine via casualsnek/waydroid_script (GPL-3.0).
    # Used as a tool, not vendored — see BORROWED.md.
    local ws="$RUN/waydroid_script"
    if [[ ! -d $ws ]]; then
        log "cloning casualsnek/waydroid_script..."
        git clone --depth 1 https://github.com/casualsnek/waydroid_script "$ws"
    fi
    cd "$ws"
    python -m venv venv 2>/dev/null || true
    ./venv/bin/pip install -q -r requirements.txt
    log "installing libndk (ARM translation for AMD) + widevine..."
    sudo ./venv/bin/python main.py install libndk widevine
    log "done. For Play Store login, also run:"
    log "  sudo $ws/venv/bin/python main.py certified"
    log "and register the printed android_id at https://www.google.com/android/uncertified"
}

# ------------------------------------------------------------------- up ----
cmd_up() {
    systemctl is-active -q waydroid-container.service \
        || sudo systemctl start waydroid-container.service

    if [[ -f $RUN/sway.pid ]] && kill -0 "$(cat "$RUN/sway.pid")" 2>/dev/null; then
        log "already up (sway pid $(cat "$RUN/sway.pid"), display $(cat "$RUN/wayland-display" 2>/dev/null || echo '?'))"
        return
    fi

    cat > "$RUN/sway.conf" <<EOF
# generated by start.sh — headless phone-geometry session for waydroid
output HEADLESS-1 mode --custom ${W}x${H}@${HZ}Hz
default_border none
xwayland disable
exec waydroid show-full-ui
EOF

    log "starting headless sway (${W}x${H}@${HZ})..."
    SOCKS_BEFORE=$(cd "${XDG_RUNTIME_DIR:?}" && ls wayland-* 2>/dev/null | grep -v '\.lock$' | sort || true)
    # Pure headless: the libinput backend needs a seat (logind/seatd) and dies
    # without one. We don't need it — touch is injected inside Android itself
    # via the scrcpy control protocol, so sway is capture-only.
    WLR_BACKENDS=headless \
        sway -c "$RUN/sway.conf" >"$RUN/sway.log" 2>&1 &
    echo $! > "$RUN/sway.pid"

    # sway doesn't reliably log its socket name — detect it as the wayland-*
    # socket that appears in XDG_RUNTIME_DIR after launch.
    local disp=""
    for _ in $(seq 1 50); do
        disp=$(comm -13 <(sort <<<"$SOCKS_BEFORE") \
                        <(cd "${XDG_RUNTIME_DIR:?}" && ls wayland-* 2>/dev/null | grep -v '\.lock$' | sort) | head -1)
        [[ -n $disp ]] && break
        kill -0 "$(cat "$RUN/sway.pid")" 2>/dev/null || { tail -5 "$RUN/sway.log" >&2; die "sway died on startup (see .run/sway.log)"; }
        sleep 0.2
    done
    [[ -n $disp ]] || die "couldn't detect sway's wayland display (see .run/sway.log)"
    echo "$disp" > "$RUN/wayland-display"

    log "up ✓  wayland display: $disp — android is booting inside it"
    log "streamer hookup: WAYLAND_DISPLAY=$disp (nx-streamerd / './start.sh ref' for sunshine baseline)"
}

# --------------------------------------------------------------- stream ----
cmd_stream() {
    [[ -f $RUN/wayland-display ]] \
        || die "no session to capture — run ./start.sh up first (needs .run/wayland-display)"
    local disp fps port
    disp=$(cat "$RUN/wayland-display")
    fps=${NXAS_FPS:-60}
    port=${NXAS_PORT:-8765}

    kill -0 "$(cat "$RUN/sway.pid" 2>/dev/null || echo 0)" 2>/dev/null \
        || die "sway isn't running (stale .run/wayland-display) — ./start.sh up"
    # v0.1 injects touch inside android over scrcpy's control socket, which
    # needs adb to reach the waydroid container. Video streams without it.
    need adb || log "note: adb not found — touch injection is disabled (pacman -S"
    need adb || log "      android-tools). Video still streams; --input none silences it."

    # The session runs at ${HZ}Hz; v0.1 streams $fps and lets the client pace.
    log "streaming ${W}x${H}@${fps} from $disp on port $port — Ctrl-C to stop"
    log "phone client: http://<pc-address>:$port  (over tailscale/wireguard)"
    exec python "$ROOT/server/nx-streamerd.py" \
        --wayland-display "$disp" \
        --width "$W" --height "$H" --fps "$fps" \
        --bitrate "${NXAS_BITRATE:-12000}" \
        --port "$port" "$@"
}

# --------------------------------------------------------------- doctor ----
cmd_doctor() {
    # Waydroid network + adb repair. The classic failure: Android never sends a
    # DHCP request (dnsmasq logs zero DISCOVERs), so the container has no IP,
    # no internet, and adb can't reach it. We look inside, fall back to a
    # static config on the waydroid bridge, and pre-authorize the host's adb
    # key so touch injection needs no accept-tap inside an invisible session.
    local wip=192.168.240.112 gw=192.168.240.1
    waydroid status 2>/dev/null | grep -q "Session:.*RUNNING" || die "session not running — ./start.sh up first"

    log "inside view of eth0:"
    sudo waydroid shell -- /system/bin/sh -c 'ip addr show eth0 2>/dev/null; ip route 2>/dev/null' || die "waydroid shell failed"

    if ! sudo waydroid shell -- /system/bin/sh -c 'ip addr show eth0 2>/dev/null' | grep -q 'inet '; then
        log "eth0 has no IPv4 — applying static config $wip/24 via $gw"
        sudo waydroid shell -- /system/bin/sh -c "
            ip link set eth0 up
            ip addr add $wip/24 dev eth0 2>/dev/null || true
            ip route add default via $gw 2>/dev/null || true
            setprop net.eth0.dns1 $gw"
    fi

    log "connectivity from inside:"
    sudo waydroid shell -- /system/bin/sh -c \
        "ping -c1 -W2 $gw >/dev/null 2>&1 && echo '  bridge: OK' || echo '  bridge: FAIL'
         ping -c1 -W2 1.1.1.1 >/dev/null 2>&1 && echo '  wan:    OK' || echo '  wan:    FAIL (host may need masquerade for 192.168.240.0/24)'
         ping -c1 -W2 google.com >/dev/null 2>&1 && echo '  dns:    OK' || echo '  dns:    FAIL'" || true

    log "authorizing host adb key + enabling adbd on tcp/5555..."
    [[ -f $HOME/.android/adbkey.pub ]] || { log "  generating adb key..."; adb keygen "$HOME/.android/adbkey" >/dev/null 2>&1 || true; adb start-server >/dev/null 2>&1 || true; }
    [[ -f $HOME/.android/adbkey.pub ]] || die "no $HOME/.android/adbkey.pub — install android-tools and run 'adb start-server' once"
    sudo mkdir -p /var/lib/waydroid/data/misc/adb
    if ! sudo grep -qsf "$HOME/.android/adbkey.pub" /var/lib/waydroid/data/misc/adb/adb_keys 2>/dev/null; then
        sudo sh -c "cat '$HOME/.android/adbkey.pub' >> /var/lib/waydroid/data/misc/adb/adb_keys"
        sudo chmod 640 /var/lib/waydroid/data/misc/adb/adb_keys
    fi
    sudo waydroid shell -- /system/bin/sh -c 'setprop service.adb.tcp.port 5555; setprop ctl.restart adbd'

    sleep 2
    if adb connect "$wip:5555" 2>/dev/null | grep -q connected; then
        log "adb: connected to $wip:5555 ✓ (boot_completed=$(adb -s "$wip:5555" shell getprop sys.boot_completed 2>/dev/null | tr -d '\r'))"
    else
        log "adb: could not connect — re-run doctor once Android finishes booting"
    fi
}

# ----------------------------------------------------------------- down ----
cmd_down() {
    waydroid session stop 2>/dev/null || true
    if [[ -f $RUN/sway.pid ]]; then
        kill "$(cat "$RUN/sway.pid")" 2>/dev/null || true
        rm -f "$RUN/sway.pid" "$RUN/wayland-display"
    fi
    log "down."
}

# --------------------------------------------------------------- status ----
cmd_status() {
    printf 'container : %s\n' "$(systemctl is-active waydroid-container.service 2>/dev/null || echo inactive)"
    if [[ -f $RUN/sway.pid ]] && kill -0 "$(cat "$RUN/sway.pid")" 2>/dev/null; then
        printf 'sway      : running (pid %s, display %s, %sx%s@%s)\n' \
            "$(cat "$RUN/sway.pid")" "$(cat "$RUN/wayland-display" 2>/dev/null || echo '?')" "$W" "$H" "$HZ"
    else
        printf 'sway      : not running\n'
    fi
    printf 'session   : %s\n' "$(waydroid status 2>/dev/null | sed -n 's/^Session:[[:space:]]*//p' || echo unknown)"
}

# ------------------------------------------------------------------ ref ----
cmd_ref() {
    # Reference rig: Sunshine capturing our headless session, for latency
    # baselines to beat. Pair from the phone with Moonlight, custom res WxH.
    need sunshine || die "sunshine not installed (pacman -S sunshine) — optional, only for baselines"
    [[ -f $RUN/wayland-display ]] || die "session not up — run ./start.sh up first"
    log "starting sunshine against $(cat "$RUN/wayland-display") — Ctrl-C to stop"
    WAYLAND_DISPLAY=$(cat "$RUN/wayland-display") sunshine
}

# ----------------------------------------------------------------- main ----
case "${1:-help}" in
    setup)  cmd_setup ;;
    arm)    cmd_arm ;;
    up)     cmd_up ;;
    stream) cmd_stream "${@:2}" ;;
    down)   cmd_down ;;
    status) cmd_status ;;
    doctor) cmd_doctor ;;
    ref)    cmd_ref ;;
    *)      sed -n '2,4p' "$0" | sed 's/^# //'; exit 1 ;;
esac
